MUE/config/routes.rb
Rails.application.routes.draw do
  resources :contacts, except: [:edit]
  get 'contacts/:id/join', to: 'contacts#join_new'
  post 'contacts/:id/create' => 'contacts#join_create'



  get 'blogcomments/new'
  post 'blogcomments' => 'blogcomments#create'


  get 'blogs/new_category'
  post 'blogs/new_category' => 'blogs#create_category'
  resources :blogs


  resources :sections
  root 'homes#home'
  get 'overview', to: 'homes#overview'
  get 'about', to: 'homes#about'
  get 'top', to: 'homes#top'
  get 'questionnaire/:id', to: 'homes#questionnaire', as: 'questionnaire'
  post 'questionnaire_create/:id', to: 'homes#questionnaire_create', as: 'questionnaire_create'
  get 'schedule/:id', to: 'homes#schedule', as: 'schedule'
  get 'homes/showDetailSchedule'
  resources :homes
  resources :caves
  resources :regions
  resources :prefectures
  resources :cities
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
  resources :admins
  resources :teachers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

MUE/app/views/layouts/_head.html.erb
<%= analytics_init if Rails.env.production? %>
<%= favicon_link_tag('favicon.ico') %>
<%= csrf_meta_tags %>
<%= csp_meta_tag %>
<meta name="viewport" content="width=device-width,initial-scale=1.0", viewport-fit=cover">
<%= display_meta_tags(default_meta_tags) %>

MUE/app/views/layouts/about_layout.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= analytics_init if Rails.env.production? %>
    <%= favicon_link_tag('favicon.ico') %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width,initial-scale=1.0", viewport-fit=cover">
    <%= display_meta_tags(default_meta_tags) %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Cookie|Dancing+Script|Great+Vibes|Parisienne|Tangerine&display=swap" rel="stylesheet">
    <!-- slick -->
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"/>
    <script type="text/javascript" src="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>
  </head>

  <body>
    <menu>
      <input id="menu_button_input" type="checkbox">
      <div id="head">
        <div id="logo">
          <%= image_tag("top/logo.png", id: "logo-image-top") %>
          <span id="name">
            <span class="name1">
              Meet up English
            </span>
            <span class="name2">
              日常に留学を
            </span>
          </span>
        </div>
        <label id="menu_button" for="menu_button_input"><div id="humberger"> <div></div><div></div><div></div></div><div class="my_times"><span></span></div></label>
      </div>
      <div id="items">
        <a href=<%= top_path %> id="to_top">TOP<span></span></a>
        <a href=<%= about_path %>>ABOUT<span></span></a>
        <a href=<%= root_path %> data-turbolinks="false">SHCEDULE<span></span></a>
        <a href=<%= blogs_path(event_search: "開催の様子") %> data-turbolinks="false">BLOG<span></span></a>
      </div>
    </menu>

    <main>
      <%= yield %>

      <div id="create_contact"></div>
      <div class="contact-top">
          <a class="contact_btn" href=<%= (session[:role]  == "Admin") ? "/contacts" : "/contacts/new" %> <%= "data-remote='true'" unless(session[:role]  == "Admin") %>>
            <span class="">
              お問い合わせはこちら
            </span>
          </a>
      </div>

      <footer class="footer-top">
        <div id="SNS">
          <span id="title">OFFICIAL&nbsp;&nbsp;&nbsp;&nbsp;ACCOUNT</span>
          <div id="button">
              <%= link_to simple_format('<i class="fab fa-youtube"></i>'), "https://www.youtube.com/channel/UC1OTguN4K5GNf8I5ZeJZkGg", class: 'youtube-footer' %>
              <%= link_to simple_format('<i class="fab fa-twitter"></i>'), "https://twitter.com/meetup_english?ref_src=twsrc%5Etfw", class: 'twitter' %>
              <%= link_to simple_format('<i class="fab fa-instagram"></i>'), "https://www.instagram.com/meet_up_english?ref=badge", class: 'instagram' %>
              <%= link_to simple_format('<i class="fab fa-facebook-square"></i>'), "https://www.facebook.com/Meet-Up-English-101228061233520/?modal=admin_todo_tour", class: 'facebbok' %>
          </div>
        </div>
        <div id="links" class="onlysp">
          <%= link_to '概要', about_path %>
          <%= link_to '開催スケジュール', root_path, data: {"turbolinks"=>false} %>
          <%= link_to 'ブログ', blogs_path(event_search: "開催の様子"), data: {"turbolinks"=>false} %>
        </div>
        <span id="mail"><%= (session[:role]  == "Admin") ? (link_to "ログアウト", logout_url, method: :delete) : "mail: meetup_english-tokyo@yahoo.co.jp" %></span>
        <span class="footer3-top">© Meet up English Group</span>
      </footer>
    </main>


  </body>
</html>

MUE/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= render'layouts/head' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="create_contact"></div>

    <header>
      <div id="header1-1"><div id="header1-2"><%= link_to image_tag("logo.jpg", alt: "logo", id: 'header1-img'), top_path %></div></div>
      <div id="header2"><p id="header2-p"><%= link_to 'Meet up English', top_path, data: {"turbolinks"=>false} %></p></div>
      <% if session[:user].nil? %>
      <div id="header3"><ul><li><a data-remote="true" href="/contacts/new?title=I want to be a teacher">I want to be a teacher</a>
      </li></ul></div>
      <% elsif %>
      <div id="header3"><ul><li>name:<%=session[:user]["name"]%></li><li>role:<%=session[:role]%></li><li><%= link_to "ログアウト", logout_url, method: :delete %></li></ul></div>
      <% end %>
    </header>

    <div id="main">
      <div id="main1">
        <div id="main2">
          <%= yield %>
        </div>
      </div>
      <div id="sidebox1" class="onlypc">
        <div id="sidebox2">
          <% unless session[:user].nil? %>
            <p><%= link_to 'teacher', teachers_path %></p>
            <p><%= link_to 'contact(' + Contact.where(checked: false).size.to_s + ')', contacts_path, data: {"turbolinks"=>false}, class: Contact.where(checked: false).size > 0 ? "text_orange_gradation" : '' %></p>
            <p><%= link_to 'cafe', caves_path %></p>
            <p><%= link_to 'city', cities_path %></p>
            <p><%= link_to 'prefecture', prefectures_path %></p>
          <% end %>

          <%= link_to "カフェ開催スケジュール", root_path, class: "page_btn",style: "background-color: #179c17"%>
          <%= link_to "Group紹介", about_path, class: "page_btn", style: "background-color: #da4f4f;"%>
          <%= link_to "Meet Up English のブログ", blogs_path(event_search: "開催の様子"), class: "page_btn", style: "background-color: #1b95e0;", data: {"turbolinks"=>false} %>

          <!-- LineWidget -->
          <!-- <a class="page_btn" style="background-color: #00b900;" href="http://nav.cx/alJd5yY">
            <img alt="友達追加" border="0" height="28" src="https://scdn.line-apps.com/n/line_add_friends/btn/ja.png"></a> -->


          <!-- InstaWidget -->
          <!-- <a href="https://www.instagram.com/meet_up_english?ref=badge" class="insta_btn2">
            <i class="fab fa-instagram"></i> <span>@meet_up_english</span>
          </a> -->

          <!-- TwitterWidget -->
          <!-- <a class="page_btn" style="background-color: #1b95e0;" href="https://twitter.com/meetup_english?ref_src=twsrc%5Etfw">
            <i class="fab fa-twitter"></i><span style="font: normal normal normal 11px/18px 'Helvetica Neue',Arial,sans-serif; font-size: 13px;">Follow @meetup_english</span>
          </a> -->

          <!-- YoutubeWidget -->
          <!-- <a class="page_btn" style="background-color: #da4f4f;" href="https://www.youtube.com/channel/UC1OTguN4K5GNf8I5ZeJZkGg">
            <i class="fab fa-youtube"></i><span>Subscribe Youtube</span>
          </a> -->

          <!-- latest event -->
          <!-- <div id="latest_event">
            <div class="text">
              <p>-----------------前回の開催-----------------</p>
            </div>
            <a href="/blogs/<%= @latest_event_blog&.id %>" class="eye_catch">
              <img src='<%= @latest_event_blog.image.attachment.service.send(:object_for, @latest_event_blog.image.key).public_url if @latest_event_blog %>'>
              <div class='title'><%= @latest_event_blog&.title %></div>
            </a>
          </div> -->

        </div>
      </div>
    </div>


    <div id="footer1" class="cmn-footer">
      <div class="pagetop"> <a>↑PAGETOP</a></div>
      <a class="footer_contact_btn contact_btn" data-remote="true" href="/contacts/new"><i class="far fa-envelope"></i>Contact</a>
      <a class="footer_page_btn twitter_btn" href="https://twitter.com/meetup_english?ref_src=twsrc%5Etfw"><i class="fab fa-twitter"></i>Follow Twitter</a>
      <a class="footer_page_btn insta_btn" href="https://www.instagram.com/meet_up_english?ref=badge"><i class="fab fa-instagram"></i>Follow Instagram</a>
      <a class="footer_page_btn line_btn" href="http://nav.cx/alJd5yY"><i class="fab fa-line"></i>Follow Line</a>
      <a class="footer_page_btn youtube_btn" href="https://www.youtube.com/channel/UC1OTguN4K5GNf8I5ZeJZkGg"><i class="fab fa-youtube"></i>Subscribe Youtube</a>
      <a class="footer_page_btn facebook_btn" href="https://www.facebook.com/Meet-Up-English-101228061233520/?modal=admin_todo_tour"><i class="fab fa-facebook-f"></i>Follow Facebook</a>
      <p class="copyright">© Meet up English Group</p>
    </div>


    <!-- spにだけ表示される、ブログとかのページに行ける下に固定しているフッター -->
    <footer id="footer_application" class="onlysp">
      <a href="/" data-turbolinks="false">Schedule</a>
      <a id="footer_center" href="/about">About</a>
      <a href="/blogs?event_search=開催の様子" data-turbolinks="false">Blog</a>
    </footer>

    <%# debug(params) if Rails.env.development? %>
    <%# debug( params[:event_search] ) if Rails.env.development? %>
  </body>
</html>

MUE/app/views/layouts/simple.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= analytics_init if Rails.env.production? %>
    <%= favicon_link_tag('favicon.ico') %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width,initial-scale=1.0", viewport-fit=cover">
    <%= display_meta_tags(default_meta_tags) %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <div id="create_contact"></div>
    <%= yield %>
  </body>
</html>

MUE/app/views/layouts/student.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= analytics_init if Rails.env.production? %>
    <%= favicon_link_tag('favicon.ico') %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width,initial-scale=1.0", viewport-fit=cover">
    <%= display_meta_tags(default_meta_tags) %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <div id="create_contact"></div>
    <%= yield %>


    <!-- sessionで色付けするかjsで色付けするか -->
    <footer id="footer_student_app">
      <a id="" href="/search">
        <i class="fas fa-search <%= "active" if @at == "search" %>"></i>
      </a>
      <a id="">
        <i class="fas fa-calendar-week "></i>
      </a>
      <a href="/account">
        <i class="fas fa-smile <%= "active" if @at == "account" %>"></i>
      </a>
    </footer>
  </body>
</html>

MUE/app/views/layouts/teacher.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= analytics_init if Rails.env.production? %>
    <%= favicon_link_tag('favicon.ico') %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width,initial-scale=1.0", viewport-fit=cover">
    <%= display_meta_tags(default_meta_tags) %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body style="margin-bottom: 44px">
    <div id="create_contact"></div>
    <!-- ここにnoticeを作る -->
    <%= yield %>



    <footer id="footer_teacher_app">
      <a href=<%= teacher_schedule_index_path %> id="">
        <i class="fas fa-calendar-week <%= "active" if @at == "schedule" %>"></i>
      </a>
      <a id="">
        <i class="fab fa-blogger-b"></i>
      </a>
      <a id="">
        <i class="fas fa-yen-sign"></i>
      </a>
      <a id="">
        <i class="fas fa-bell"></i>
      </a>
      <a href=<%= teacher_account_index_path %> id="">
        <i class="fas fa-smile <%= "active" if @at == "account" %>"></i>
      </a>
    </footer>

  </body>
</html>