MUE/config/routes.rb
Rails.application.routes.draw do
  resources :contacts, except: [:edit]
  get 'contacts/:id/join', to: 'contacts#join_new'
  post 'contacts/:id/create' => 'contacts#join_create'



  get 'blogcomments/new'
  post 'blogcomments' => 'blogcomments#create'


  get 'blogs/new_category'
  post 'blogs/new_category' => 'blogs#create_category'
  resources :blogs


  resources :sections
  root 'homes#home'
  get 'overview', to: 'homes#overview'
  get 'about', to: 'homes#about'
  get 'top', to: 'homes#top'
  get 'questionnaire/:id', to: 'homes#questionnaire', as: 'questionnaire'
  post 'questionnaire_create/:id', to: 'homes#questionnaire_create', as: 'questionnaire_create'
  get 'schedule/:id', to: 'homes#schedule', as: 'schedule'
  get 'homes/showDetailSchedule'
  resources :homes
  resources :caves
  resources :regions
  resources :prefectures
  resources :cities
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
  resources :admins
  resources :teachers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

MUE/app/models/city.rb
class City < ApplicationRecord
  belongs_to :prefecture
  has_many :events, dependent: :destroy
  #for home page
  has_many :caves, dependent: :destroy
  has_many :teachers, dependent: :destroy, foreign_key: "city_id_id"
end

MUE/app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  before_action :set_city, only: [:show, :edit, :update, :destroy]

  # GET /cities
  # GET /cities.json
  def index
    @cities = City.all
  end

  # GET /cities/1
  # GET /cities/1.json
  def show
  end

  # GET /cities/new
  def new
    @city = City.new
  end

  # GET /cities/1/edit
  def edit
  end

  # POST /cities
  # POST /cities.json
  def create
    @city = City.new(city_params)

    respond_to do |format|
      if @city.save
        format.html { redirect_to schedule_path(@city.prefecture.id), notice: 'City was successfully created.' }
        format.json { render :show, status: :created, location: @city }
      else
        format.html { render :new }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cities/1
  # PATCH/PUT /cities/1.json
  def update
    respond_to do |format|
      if @city.update(city_params)
        format.html { redirect_to @city, notice: 'City was successfully updated.' }
        format.json { render :show, status: :ok, location: @city }
      else
        format.html { render :edit }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
    unless params[:city][:image_ids].nil?
      params[:city][:image_ids].each do |image_id|
        image = @city.images.find(image_id)
        image.purge
      end
    end
  end

  # DELETE /cities/1
  # DELETE /cities/1.json
  def destroy
    @city.destroy
    respond_to do |format|
      format.html { redirect_to cities_url, notice: 'City was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_city
      @city = City.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def city_params
      params.require(:city).permit(:name, :prefecture_id)
    end
end

MUE/app/views/cities/_form.html.erb
<%= form_with(model: city, local: true) do |form| %>
  <% if city.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(city.errors.count, "error") %> prohibited this city from being saved:</h2>

      <ul>
      <% city.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>


  <div class="field">
    <%= form.label :prefecture_id %>
    <%= form.select :prefecture_id, Prefecture.all.map{|m|[m.name,m.id]} %>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

MUE/app/views/cities/edit.html.erb
<h1>Editing City</h1>
<%= render 'form', city: @city %>

<%= link_to 'Back', cities_path %>

MUE/app/views/cities/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cities</h1>
<%= link_to 'New City', new_city_path %>

<table>
  <thead>
    <tr>
      <th>Id</th>
      <th>Name</th>
      <th>Prefectureid</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cities.each do |city| %>
      <tr>
        <td><%= city.id %></td>
        <td><%= city.name %></td>
        <td><%= Prefecture.find(city.prefecture_id).name %></td>
        <td><%= link_to 'new event', new_home_path(selected_city: city.id) %></td>
        <td><%= link_to 'Edit', edit_city_path(city) %></td>
        <td><%= link_to 'Destroy', city, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

MUE/app/views/cities/new.html.erb
<h1>Create New City</h1>

<%= render 'form', city: @city %>

<%= link_to 'Back',cities_path %>

MUE/app/views/cities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @city.name %>
</p>

<p>
  <strong>Prefectureid:</strong>
  <%= @city.prefecture_id %>
</p>

<p>
  <strong>Images:</strong><br>
<% if @city.images.attached? %>
  <% @city.images.each do |image| %>
    <%= image_tag image, :size=>"400x400" %> <br>
  <% end %>
<% end %>
</p>

<%= link_to 'Edit', edit_city_path(@city) %> |
<%= link_to 'Back', cities_path %> <br>

<%= link_to 'new home', new_home_path(selected_city: @city.id) %>