MUE/config/routes.rb
Rails.application.routes.draw do
  resources :contacts, except: [:edit]
  get 'contacts/:id/join', to: 'contacts#join_new'
  post 'contacts/:id/create' => 'contacts#join_create'



  get 'blogcomments/new'
  post 'blogcomments' => 'blogcomments#create'


  get 'blogs/new_category'
  post 'blogs/new_category' => 'blogs#create_category'
  resources :blogs


  resources :sections
  root 'homes#home'
  get 'overview', to: 'homes#overview'
  get 'about', to: 'homes#about'
  get 'top', to: 'homes#top'
  get 'questionnaire/:id', to: 'homes#questionnaire', as: 'questionnaire'
  post 'questionnaire_create/:id', to: 'homes#questionnaire_create', as: 'questionnaire_create'
  get 'schedule/:id', to: 'homes#schedule', as: 'schedule'
  get 'homes/showDetailSchedule'
  resources :homes
  resources :caves
  resources :regions
  resources :prefectures
  resources :cities
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
  resources :admins
  resources :teachers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

MUE/app/models/section.rb
class Section < ApplicationRecord
  has_one_attached :image
  belongs_to :blog
  after_validation do |section|
    if section.title == "前回の開催の様子"
      category_id = 4
      this_blog = section.blog
      last_blog = Blog.where(blogcategory_id: category_id).where('created_at<?', this_blog.created_at).last
      a_href = "href='/blogs/#{last_blog.id}'"
      section.text += ("<div id='last_lesson'><a class='image' #{a_href}><img src='#{ last_blog.image.attachment.service.send(:object_for, last_blog.image.key).public_url }'></a><a class='title' #{a_href}>#{ last_blog.title }</a></div>")
    end
  end
end

MUE/app/controllers/sections_controller.rb
class SectionsController < ApplicationController
  before_action :set_section, only: [:show, :edit, :update, :destroy]

  # GET /sections
  # GET /sections.json
  def index
    @sections = Section.all
  end

  # GET /sections/1
  # GET /sections/1.json
  def show
  end

  # GET /sections/new
  def new
    @section = Section.new
  end

  # GET /sections/1/edit
  def edit
  end

  # POST /sections
  # POST /sections.json
  def create
    @section = Section.new(section_params)

    respond_to do |format|
      if @section.save
        format.html { redirect_to blog_path(@section.blog), notice: 'Section was successfully created.' }
        format.json { render :show, status: :created, location: @section }
      else
        format.html { render :new }
        format.json { render json: @section.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sections/1
  # PATCH/PUT /sections/1.json
  def update
    respond_to do |format|
      if @section.update(section_params)
        format.html { redirect_to blog_path(@section.blog), notice: 'Section was successfully updated.' }
        format.json { render :show, status: :ok, location: @section }
      else
        format.html { render :edit }
        format.json { render json: @section.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sections/1
  # DELETE /sections/1.json
  def destroy
    @selected_blog_id=@section.blog_id
    @section.destroy
    respond_to do |format|
      format.html { redirect_to blog_path(@selected_blog_id), notice: 'Section was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_section
      @section = Section.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def section_params
      params.require(:section).permit(:title, :text, :image, :blog_id, :index)
    end
end

MUE/app/helpers/sections_helper.rb
module SectionsHelper
end

MUE/app/views/sections/_form.html.erb
<div id="section_form">
  <%= form_with(model: section, local: true) do |form| %>
    <% if section.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(section.errors.count, "error") %> prohibited this section from being saved:</h2>

        <ul>
        <% section.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div id="how_to_last_event"><p class="how_to_last_event_style">前回の開催の様子のツイッターカードの作り方</p></div>
    <div class="field">
      <%= form.label :title %>
      <%= form.text_field :title %>
    </div>

    <div class="field">
      <%= form.label :text %>
      <%= form.text_area :text %>
    </div>

    <div class="field">
      <%= form.label :image %>
      <%= form.file_field :image %>
    </div>

    <div class="field" <% if params[:selected_blog] %> style="display:none" <% end %>>
      <%= form.label :blog_id %>
      <%= form.number_field :blog_id , value:params[:selected_blog]?params[:selected_blog]:0%>
    </div>

    <div class="field">
      <%= form.label :index %>
      <%= form.number_field :index , value:@section.index ? @section.index : Section.all.size%>
    </div>

    <div class="actions">
      <%= form.submit %>
    </div>
<% end %>
</div>

<script type="text/javascript">
  $('#how_to_last_event').one('click',function(e){
    console.log("hello")
    $(this).append("</p><p>Title　＝＞　前回の開催の様子<br>で作ったときにカードのhtmlコードがtextの最後に挿入されるっていう仕組み<br>注意:　editするときは、textの末尾のhtmlコードを消さないとダブる</p>");
  });
</script>
<style media="screen">
  .how_to_last_event_style{
    cursor: pointer;
    text-decoration: underline;
  }
</style>

MUE/app/views/sections/edit.html.erb
<h1>Editing Section</h1>

<%= render 'form', section: @section %>

MUE/app/views/sections/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Sections</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Text</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sections.each do |section| %>
      <tr>
        <td><%= section.title %></td>
        <td><%= section.text %></td>
        <td><%= link_to 'Show', section %></td>
        <td><%= link_to 'Edit', edit_section_path(section) %></td>
        <td><%= link_to 'Destroy', section, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Section', new_section_path %>

MUE/app/views/sections/new.html.erb
<h1>New Section</h1>

<%= render 'form', section: @section %>

MUE/app/views/sections/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @section.title %>
</p>

<p>
  <strong>Text:</strong>
  <%= @section.text %>
</p>

<%= link_to 'Edit', edit_section_path(@section) %> |
<%= link_to 'Back', sections_path %>