MUE/config/routes.rb
Rails.application.routes.draw do
  resources :contacts, except: [:edit]
  get 'contacts/:id/join', to: 'contacts#join_new'
  post 'contacts/:id/create' => 'contacts#join_create'



  get 'blogcomments/new'
  post 'blogcomments' => 'blogcomments#create'


  get 'blogs/new_category'
  post 'blogs/new_category' => 'blogs#create_category'
  resources :blogs


  resources :sections
  root 'homes#home'
  get 'overview', to: 'homes#overview'
  get 'about', to: 'homes#about'
  get 'top', to: 'homes#top'
  get 'questionnaire/:id', to: 'homes#questionnaire', as: 'questionnaire'
  post 'questionnaire_create/:id', to: 'homes#questionnaire_create', as: 'questionnaire_create'
  get 'schedule/:id', to: 'homes#schedule', as: 'schedule'
  get 'homes/showDetailSchedule'
  resources :homes
  resources :caves
  resources :regions
  resources :prefectures
  resources :cities
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
  resources :admins
  resources :teachers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

MUE/app/models/blog.rb
class Blog < ApplicationRecord
  has_one_attached :image
  has_many :comments,class_name: 'Blogcomment',dependent: :destroy
  has_many :sections,class_name: 'Section',dependent: :destroy
  belongs_to :category, class_name: 'Blogcategory', foreign_key: 'blogcategory_id'
  validates :title, :text, presence: true #nil拒否
end

MUE/app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  include Pagy::Backend
  protect_from_forgery
  before_action :set_blog, only: [:show, :edit, :update, :destroy]


  skip_before_action :require_Admin,only:[:index, :show]

  # GET /blogs
  # GET /blogs.json
  def index
    @categories = Blogcategory.all.order(:id)
    @selected_category_id = params[:event_search] ? Blogcategory.find_by(name: params[:event_search]).id : 1
    @pagy, @blogs = pagy( (@selected_category_id == 1) ? Blog.all.order('created_at desc, id desc') : Blog.where( blogcategory_id: @selected_category_id ).order('created_at desc, id desc'), items: 8 )
    render layout: 'about_layout.html.erb'
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
    @categories = Blogcategory.all.order(:id)
    @next_blog =  Blog.order('created_at desc, id desc').where(youtube: false).where('created_at >= ? and id > ?', @blog.created_at, @blog.id).reverse.first
    @before_blog =  Blog.order('created_at desc, id desc').where(youtube: false).where('created_at <= ? and id < ?', @blog.created_at, @blog.id).first
    render layout: 'about_layout.html.erb'
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  def create
    @blog = Blog.new(blog_params)
    if @blog.save
      redirect_to (@blog.youtube ? blogs_url : @blog)
    else
      render :new
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    if @blog.update(blog_params)
      redirect_to (@blog.youtube ? blogs_url : @blog)
    else
      render :edit
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    Section.where(blog_id: @blog.id).each{|n|n.destroy}
    Blogcomment.where(blog_id: @blog.id).each{|n|n.destroy}
    redirect_to blogs_url
  end

  def new_category
    @blogcategory = Blogcategory.new
  end

  def create_category
    @blogcategory = Blogcategory.new(category_params)
    if @blogcategory.save
      redirect_to blogs_url
    else
      render:new_category
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_params
      params.require(:blog).permit(:title, :text, :image, :blogcategory_id, :youtube)
    end

    def category_params
      params.require(:blogcategory).permit(:name, :image)
    end

    def event_search_params
      params.require(:event_search).permit(:keyword)
    end
end

MUE/app/helpers/blogs_helper.rb
module BlogsHelper
  include Pagy::Frontend
end

MUE/app/views/blogs/_form.html.erb
<div id="blog_form">
  <%= form_with(model: blog, local: true) do |form| %>
    <% if blog.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

        <ul>
        <% blog.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= form.label :youtube %>youtubeを投稿する場合はcheck!->
      <%= form.check_box :youtube %>
    </div>

    <div class="field">
      <%= form.label :title %>
      <%= form.text_field :title %>
    </div>

    <div class="field">
      <%= form.label :text %>youtubeを投稿する場合はurlをの'v='以降<br>例)https://www.youtube.com/watch?v=eSPs9a2qpIw のとき eSPs9a2qpIw<br>
      <%= form.text_area :text%>
    </div>

    <div class="field">
      <%= form.label :image %>youtubeを投稿する場合は指定なし<br>
      <%= form.file_field :image %>
    </div>

    <div class="field">
      <%= form.label :blogcategory_id %>
      <%= form.select :blogcategory_id, Blogcategory.all.map{|m| [m.name,m.id]} %>
    </div>

    <%= link_to 'Click here to create new category', blogs_new_category_path %>

    <div class="actions">
      <%= form.submit %>
    </div>
  <% end %>
</div>

MUE/app/views/blogs/edit.html.erb
<h1>Editing Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blogs_path %>

MUE/app/views/blogs/index.html.erb
<% set_meta_tags title: 'Groupの活動の様子をブログでみちゃおう！', description: 'Meet Up English Groupの「開催日記」「旅日記」「ご飯日記」「先生日記」「スタッフ日記」などなど、いろいろな情報を発信しております。
開催時の様子や、先生の紹介など、【毎日更新】を続けておりますので、ご覧ください。'%>

<div id="blog_index">
  <div id="eyecatch"><%= image_tag("homes/blog.jpg", alt: "image of MeetupEnglishGroup Blog") %></div>
  <div id="pankuzu">
    <a href="/top">TOP</a><i class="fas fa-chevron-right"></i>
    <span>BLOG(<%= params[:event_search]||'all' %>)</span>
  </div>


  <% if session[:role]=="Admin" %><p id="notice"><%= notice %></p><% end %>
  <%= if session[:role]=="Admin" then link_to 'New Blog', new_blog_path end%>


  <div id="other">
    <div id="category">
      <h3 id="category-title">Category</h3>
      <div id="name">
        <% @categories.each do |category| %>
          <a class="item <%= "active" if (category.id ) == @selected_category_id %>" href="/blogs?event_search=<%= category.name %>" data-turbolinks="false">
            <%= category.name %>(<%= category.id == 1 ? Blog.count : category.blogs.count %>)
          </a>
        <% end %>
      </div>
    </div>

    <div id="articles">
      <div class="skill-list jscroll">
        <% if @blogs %>
          <% @blogs.each do |blog| %>

            <% if !blog.youtube? %>
              <a href="/blogs/<%= blog.id %>"id="blog">
                <div class="eyecatch">
                  <% if blog.image.attached? %>
                    <%= image_tag blog.image, :size=>"400x400" %>
                  <% end %>
                </div>
                <h3><%= blog.title %></h3>
                <div class="explain">
                  <div class="explain-1">
                    <div class="category">
                      カテゴリー:<%= blog.category&.name %>
                    </div>
                    <div class="blog_createdAt">
                      <% if session[:role]=="Admin" %><%= link_to 'Edit', edit_blog_path(blog)%> | <%= link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' } %><%end%>
                      <%= blog.created_at.strftime("%Y.%m.%d") %>
                    </div>
                  </div>
                  <div class="commentnum_blog_index"><i class="fas fa-comments"></i><%= blog.comments.count %></div>
                </div>
              </a>
            <% else %>

              <a id="blog" class="youtube" href="https://www.youtube.com/watch?v=<%= blog.text %>">
                <div class="eyecatch">
                  <iframe width="560" height="315" src="https://www.youtube.com/embed/<%= blog.text %>" data-src="https://www.youtube.com/embed/<%= blog.text %>" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                </div>
                <h3><%= blog.title%></h3>
                <div class="explain">
                  <div class="explain-1">
                    <div class="category">
                      カテゴリー:<%= blog.category&.name %>
                    </div>
                    <div class="blog_createdAt">
                      <% if session[:role]=="Admin" %><%= link_to 'Edit', edit_blog_path(blog)%> | <%= link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' } %><%end%>
                      <%= blog.created_at.strftime("%Y.%m.%d") %>
                    </div>
                  </div>
                </div>
              </a>

            <% end %>

          <% end %>
        <% end %>

        <%== pagy_nav(@pagy) %>
      </div>



    </div>
  </div>

</div>

MUE/app/views/blogs/new.html.erb
<h1>New Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Back', blogs_path %>

MUE/app/views/blogs/new_category.html.erb
<h1>New Category</h1>

<%= form_with(model: @blogcategory, local: true,url: '') do |form| %>
  <% if @blogcategory.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@blogcategory.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
      <% @blogcategory.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>



  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name%>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

MUE/app/views/blogs/show.html.erb
<% set_meta_tags title: @blog.title, description: @blog.text,og: { image: @blog.image.attachment.service.send(:object_for, @blog.image.key).public_url }%>

<div id="create_comment"></div>

<div id="blog_paht">


  <div id="header">
    <%= image_tag 'homes/officialblog.png' %>
    <div id="categories"><% @categories.each do |category| %>
      <a href="/blogs?event_search=<%= category.name %>"><%= category.name %></a>
    <% end %></div>
  </div>

  <div id="pankuzu">
    <a href="/top">TOP</a><i class="fas fa-chevron-right"></i>
    <a href=<%= blogs_path(event_search: @blog.category.name) %>>BLOG(<%= @blog.category.name %>)</a><i class="fas fa-chevron-right"></i>
    <span><%= @blog.title.truncate(20) %></span>
  </div>

  <div class="around_blog">
    <a class="left_blog" href="/blogs/<%= @next_blog&.id %>"><i></i><span><%= @next_blog&.title %></span></a>
    <a class="right_blog" href="/blogs/<%=  @before_blog&.id %>"><span><%= @before_blog&.title %></span><i></i></a>
  </div>

  <!-- タイトル本文 -->
  <div id="title">
    <h1><%= @blog.title %></h1>
    <p id="date" ><%= @blog.created_at.strftime("%Y年%m月%d日") %></p>
  </div>
  <div id="title_text">
    <%= image_tag @blog.image, class: "blog_image"%>
    <%=  if session[:role]=="Admin" then link_to 'EditBlog', edit_blog_path(@blog) end %>
    <p class="text"><%= raw(@blog.text.gsub(/\n/, '<br>')) %></p>
  </div>




  <!-- 目次 -->
  <!-- <div class="toc_container">
  <p >この記事の目次</p>
  <ul style="display: block;">
  <% @blog.sections.order(:index).each do |n| %>
      <li><a href="#blogIndex<%= n.id %>"><%= n.title %></a></li>
  <% end %>
  <li><a href="#blog_index_comment">コメント</a></li>
  </ul>
  </div> -->



  <!-- セクション -->
  <div id="sections">
    <section id="blog_section">
      <%= if session[:role]=="Admin" then link_to 'NewSection', new_section_path(selected_blog:@blog.id) end %>
      <% @blog.sections.order(:index).each do |n| %>
        <h2 id="blogIndex<%= n.id %>"><%= n.title %></h2>
        <% if session[:role]=="Admin" %><%= link_to 'EditSection', edit_section_path(n.id,selected_blog:@blog.id) %> | <%= link_to 'DestroySection', n, method: :delete, data: { confirm: 'Are you sure?' } %><% end %>
        <% if n.image.attached? %>
        <%= image_tag n.image, class: "section_image"%>
        <% end %>
        <p><%= raw(n.text.gsub(/\n/, '<br>')) %></p>
      <% end %>
    </section>
  </div>


  <p id="posted_on">Posted on <%= @blog.created_at.strftime("%Y年%m月%d日") %></p>

  <!-- 前後のブログ -->
  <div class="around_blog">
    <a class="left_blog" href="/blogs/<%= @next_blog&.id %>" data-turbolinks="false"><i></i><span><%= @next_blog&.title %></span></a>
    <a class="right_blog" href="/blogs/<%=  @before_blog&.id %>" data-turbolinks="false"><span><%= @before_blog&.title %></span><i></i></a>
  </div>


  <!-- コメント -->
  <div id="blog_index_comment">
    <a data-remote="true" href="/blogcomments/new?blogId=<%= @blog.id %> "> <i class="fas fa-comments"></i>コメントする</a></div>

  <table id="blog_comments"><tbody>
    <tr><th>コメント(<%= @blog.comments.size %>)</th></tr>
    <% @blog.comments.to_enum.with_index.reverse_each do |n, index| %><!-- .to_enum.with_index => index付与 -->
    <tr><td class="number_blog_comments"><%= index+1 %></td><td><%= simple_format(n.text) %><div><%= n.name %></div><div class="created_blog_comments"><%= n.created_at.strftime("%Y/%m/%d %H:%M:%S") %></div></td></tr>
    <% end %>
  </tbody></table>
</div>